// <auto-generated />
namespace FilmWorldCinemaProject_MVC_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newrelatl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newrelatl));
        
        string IMigrationMetadata.Id
        {
            get { return "202103260659016_newrelatl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
